# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = ""
name = "Friends-Family-Discount"
application_url = ""
embedded = true

[webhooks]
api_version = "2025-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_customers,read_orders,write_orders,read_products,write_discounts,read_discounts,read_checkouts,write_checkouts"
optional_scopes = []
use_legacy_install_flow = false

[auth]
redirect_urls = []

